### ISSUE TITLE
VIVE Cosmos

### ISSUE THREAD

**Issue by benjha** [timdecode/LifeBrush#1]
Thanks for sharing your code.

Any thoughts about if LifeBrush  will work on the VIVE Cosmos ?

**Comment by timdecode** [comment]
Thanks for checking it out! I haven't tried the Cosmos yet. However I am using SteamVR and SteamVRInput so it might work. The settings can be remapped in: 

`/Config/DefaultInput.ini`

I'm submitting my thesis in a few weeks, afterwards I'll see if I can get my hands on one to test.

**Comment by timdecode** [comment]
I have updated the code to work with other headsets. I haven't tried the Cosmos yet, but it should work. The controls use the A,B, the trigger, the grip buttons, and the select/menu buttons.
